package com.tstyle.dao;

import com.tstyle.po.SysCode;

public interface SysCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    int insert(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    int insertSelective(SysCode record);
}