package com.tstyle.dao;

import com.tstyle.po.SysRoleResource;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    int insertSelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    SysRoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    int updateByPrimaryKeySelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    int updateByPrimaryKey(SysRoleResource record);
}