package com.tstyle.po;

public class SysCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.CODE_TYPE
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    private String codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.CODE_C_TYPE
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    private String codeCType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.CODE_VALUE
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    private String codeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.CODE_NAME
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    private String codeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.STATUS_CD
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    private String statusCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.CODE_TYPE
     *
     * @return the value of sys_code.CODE_TYPE
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.CODE_TYPE
     *
     * @param codeType the value for sys_code.CODE_TYPE
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.CODE_C_TYPE
     *
     * @return the value of sys_code.CODE_C_TYPE
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public String getCodeCType() {
        return codeCType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.CODE_C_TYPE
     *
     * @param codeCType the value for sys_code.CODE_C_TYPE
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public void setCodeCType(String codeCType) {
        this.codeCType = codeCType == null ? null : codeCType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.CODE_VALUE
     *
     * @return the value of sys_code.CODE_VALUE
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.CODE_VALUE
     *
     * @param codeValue the value for sys_code.CODE_VALUE
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.CODE_NAME
     *
     * @return the value of sys_code.CODE_NAME
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.CODE_NAME
     *
     * @param codeName the value for sys_code.CODE_NAME
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code.STATUS_CD
     *
     * @return the value of sys_code.STATUS_CD
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code.STATUS_CD
     *
     * @param statusCd the value for sys_code.STATUS_CD
     *
     * @mbggenerated Sat Jan 20 16:19:48 CST 2018
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }
}